# Remove the version line as it's obsolete
services:
  # Game server
  game-server:
  build: ./game-server
  container_name: game-server
  environment:
    - NODE_ENV=production
    - SUPABASE_URL=${SUPABASE_URL}
    - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
  networks:
    - app-network
  restart: unless-stopped

  # Chat server - fix the path case
  chat-server:
    build: ./Server  # Capital S to match your directory
    container_name: chat-Server
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CHAT_PORT=3002
    networks:
      - app-network
    restart: unless-stopped

  # Redis (if you need it)
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - game-server
      - chat-server
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge